name: Firebase Hosting Merge

on:
  push:
    branches:
      - APPR6312

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to latest version

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Updated to latest version
        with:
          node-version: '16' # or '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DISASTERALLEVIATION_FOUNDATION }}'
          channelId: live
          projectId: disasteralleviation-foundation
          entryPoint: ./
